In [1]:
import numpy as np
np.__version__

'1.16.4'

np? #'?' gives the documentation and other relevant info. can also use help(..) to get access to the documentation.

np.absolute_import??# ?? enables to access the source code of the object we are curious to know about

np.<TAB> # use of the Tab key for autocompletion and exploration of the contents of objects, modules, and namespaces

In [2]:
#creating arrays from lists in python. Mentioning the data type of the resulting array explicitly is not
#always required.
A=np.array([1,2,3,4],dtype='int32')
#or dtype could also be mentioned by using the associated numpy object rather than using string
A=np.array([1,2,3,4],dtype=np.int32)
# Create a length-10 integer array filled with zeros        
np.zeros(10, dtype=int)
# Create a 3x5 floating-point array filled with 1s  
np.ones((3, 5), dtype=float)
# Create a 3x5 array filled with 3.14       
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [3]:
# Create an array filled with a linear sequence  
# Starting at 0, ending at 20, stepping by 2      
# (this is similar to the built-in range() function)        
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
# Create an array of five values evenly spaced between 0 and 1        
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
# Create a 3x3 array of uniformly distributed        
# random values between 0 and 1        
np.random.random((3, 3))

# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1        
np.random.normal(0, 1, (3, 3))

# Create a 3x3 array of random integers in the interval [0, 10)        
np.random.randint(0, 10, (3, 3))

# Create a 3x3 identity matrix        
np.eye(3)

np.random.seed(0) #seed with a set value(here 0) in order to ensure that the same random arrays are generated every
#time the code is run

x1=np.random.randint(0,10,(3,4,5))#every array has these 3 attributes: ndim(number of dimensions),shape and size of
#array. Other attributes include dtype, itemsize, nbytes, etc
print(x1.ndim)
print(x1.shape)
print(x1.size)
print(x1.dtype)
print(x1.itemsize) #lists the size(in bytes) of each array element
print(x1.nbytes) #lists the total size(in bytes) of the array
print(x1)
print(x1[0,0,2]) #in multi-dimensional arrays, u access items using comma separated tuple of indices
x1[0,0,1]=2
print(x1)

3
(3, 4, 5)
60
int32
4
240
[[[5 0 3 3 7]
  [9 3 5 2 4]
  [7 6 8 8 1]
  [6 7 7 8 1]]

 [[5 9 8 9 4]
  [3 0 3 5 0]
  [2 3 8 1 3]
  [3 3 7 0 1]]

 [[9 9 0 4 7]
  [3 2 7 2 0]
  [0 4 5 5 6]
  [8 4 1 4 9]]]
3
[[[5 2 3 3 7]
  [9 3 5 2 4]
  [7 6 8 8 1]
  [6 7 7 8 1]]

 [[5 9 8 9 4]
  [3 0 3 5 0]
  [2 3 8 1 3]
  [3 3 7 0 1]]

 [[9 9 0 4 7]
  [3 2 7 2 0]
  [0 4 5 5 6]
  [8 4 1 4 9]]]


In [6]:
x=np.arange(10)
#slicing of arrays in numpy can be done as follows: x[start:stop:step].
#if any of these values are missing the default values are: start=0, stop=size of dimension,step=1
print(x[:5]) #first five elements
print(x[5:]) #elements after index 5
print(x[4:7]) #middle subarray
print(x[1::2]) #every other element starting at index 1

#when step value is negative, the defaults for start and stop value are swapped

print(x[::-1]) #all elements are reversed
print(x[5::-2]) #reversed every other from index 5 till index 0

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


In [7]:
#Multidimensional slices work in the same way, with multiple slices separated by commas
x2=np.random.randint(0,10,(4,4))
print(x2[:,0]) #accessing the first column of x2
print(x2[0,:]) #accessing the first row of x2
x3=x2[:2,:2].copy() #copy() method is used to explicitly copy data within an array or subarray. By default array slices
#in numpy return views rather than copies of the array data. This is one area in which Numpy array slicing differs from
#Python list slicing: in lists, slices will be copies.
print(x3)

[8 9 7 5]
[8 1 1 7]
[[8 1]
 [9 9]]


In [8]:
x=np.arange(1,10).reshape((3,3))# Wherever possible, the reshape method will use no-copy view of the initial array,
#but with non-contiguous memory buffers this isnt always the case
print(x)
x=np.array([1,2,3])
x.reshape((1,3))#row vector via reshape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3]])

In [9]:
x[np.newaxis,:]#row vector via numpy's newaxis  keyword

array([[1, 2, 3]])

In [10]:
#Concatenation or joining of two or more arrays in Numpy is primarily accomplished through the routines np.concatenate,
#np.vstack, np.hstack
x=np.array([1,2,3])
y=np.array([3,2,1])
print(np.concatenate([x,y])) #this method takes a tuple or list of arrays to be concatenated
#np.concatenate can also be used for 2-D arrays
grid=np.arange(10).reshape((5,2))
print(np.concatenate([grid,grid])) #concatenate along the first axis
np.concatenate([grid,grid],axis=1)#concatenated along the second axis

#The axis keyword specifies the dimension of the array that will be collapsed rather than the dimension of the array
#that will be returned

[1 2 3 3 2 1]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]
 [0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

In [11]:
#For working with arrays of mixed dimensions, it can be clearer to use np.vstack and np.hstack functions
x=np.array([1,2,3])
grid=np.array([[9,8,7],[6,5,4]])
print(np.vstack([x,grid]))# vertically stack the arrays, i.e concatenating along the first axis

[[1 2 3]
 [9 8 7]
 [6 5 4]]


In [12]:
y=np.array([[99],[99]])
print(np.hstack([grid,y])) #horizontally stack the arrays, i.e. concatenating along the second axis
#similarly np.dstack() will stack arrays along the thrid axis

[[ 9  8  7 99]
 [ 6  5  4 99]]


In [13]:
#The opposite of concatenation is splitting, which is accomplished by the functions np.split, np.hsplit and np.vsplit
x=np.array([1,2,3,99,99,3,2,1])
x1,x2,x3 = np.split(x,[3,5]) #the list of indices passed as argument gives the split points. N split points lead to N+1
#subarrays
print(x1,x2,x3)
grid=np.arange(16).reshape((4,4))
upper, lower=np.vsplit(grid,[2]) #splits along the first axis
print(upper)
print(lower)
left,right=np.hsplit(grid,[3]) #splits along the second axis
print(left)
print(right)
#np.dsplit will split along the third axis

[1 2 3] [99 99] [3 2 1]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]


Exploring Numpy's Ufuncs(i.e. Universal Functions)

In [14]:
x=np.arange(4)
print("x=",x)
print("x+5=",x+5) #equivalent to np.add(x,5)
print("x-5=",x-5) #equivlent to np.subtract(x,5)
print("-x=",-x) #equivalent to np.negative(x)
print("x*2=",x*2) #equivalent to np.multiply(x,2)
print("x/2=",x/2) #equivalent to np.divide(x,2)
print("x//2=",x//2) #equivalent to np.floor_divide(x,2)
print("x**2=",x**2)#equivalent to np.power(x,2)
print("X%2=",x%2) #equivalent to np.mod(x,2)
print("abs(x)=",abs(x)) #equivalent to np.abs(x)

x= [0 1 2 3]
x+5= [5 6 7 8]
x-5= [-5 -4 -3 -2]
-x= [ 0 -1 -2 -3]
x*2= [0 2 4 6]
x/2= [0.  0.5 1.  1.5]
x//2= [0 0 1 1]
x**2= [0 1 4 9]
X%2= [0 1 0 1]
abs(x)= [0 1 2 3]


In [15]:
#Trigonometric universal functions
theta=np.linspace(0,np.pi,3)
print("sin(theta)=",np.sin(theta)) #inverse of sin function is given by np.arcsin()
print("cos(theta)=",np.cos(theta))#inverse is given by np.arccos()
print("tan(theta)=",np.tan(theta))#inverse tan function is given by np.arctan()

sin(theta)= [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)= [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)= [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [16]:
#Exponents and Logarithms
x=[1,2,3]
print("e^x=",np.exp(x))
print("2^x=",np.exp2(x))
print("3^x=",np.power(3,x))

#inverse of exponentials - logarithms
x=[1,2,4,10]
print("ln(x)=",np.log(x)) #gives the natural logarithm
print("log2(x)=",np.log2(x)) #base-2 logarithm
print("log10x=",np.log10(x)) #base-10 logarithm

e^x= [ 2.71828183  7.3890561  20.08553692]
2^x= [2. 4. 8.]
3^x= [ 3  9 27]
ln(x)= [0.         0.69314718 1.38629436 2.30258509]
log2(x)= [0.         1.         2.         3.32192809]
log10x= [0.         0.30103    0.60205999 1.        ]


In [17]:
#for comparison and bitwise operators, and for aggregate functions refer Python data science handbook

In [22]:
#Fancy indexing - passing an array of indices to access multiple array elements at once
x=np.random.randint(100,size=10)
print(x)
print([x[3],x[5],x[8]]) #one way of fancy indexing
indices=[3,5,8]
print(x[indices]) #alternative way of fancy indexing

#With fancy indexing, the shape of the result reflects the shape of the index arrays rather than the shape of the array
#being indexed
indices = np.array([[1,2],[5,7]])
print(x[indices])
#Fancy indexing also works in multiple dimensions
print('***')
X=np.arange(12).reshape((3,4))
print(X)
row=np.array([0,1,2])
col=np.array([2,1,3])
print(X[row,col]) #the first index refers to the row and the second index refers to the column
print(X[row[:,np.newaxis],col]) #each row value is matched with each column vector as we saw in broadcasting

#to know more about how np.newaxis works, visit this site:
#https://stackoverflow.com/questions/29241056/how-does-numpy-newaxis-work-and-when-to-use-it

[46 42 56 60 77 30 24  2  3 94]
[60, 30, 3]
[60 30  3]
[[42 56]
 [30  2]]
***
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 2  5 11]
[[ 2  1  3]
 [ 6  5  7]
 [10  9 11]]


Sorting of arrays

In [19]:
x=np.array([2,1,4,3,5])
print(np.sort(x)) #returns a sorted version of the array without modifying the input
x.sort() #to sort the array in-place, we can use the sort() method of arrays
print(x)
x=np.array([1,2,5,4,6])
print(np.argsort(x)) #returns the indices of the sorted elements

[1 2 3 4 5]
[1 2 3 4 5]
[0 1 3 2 4]


In [21]:
X=np.random.randint(0,10,(4,6))
print(X)
print('***')
print(np.sort(X,axis=0)) #sort each column of X
print(np.sort(X,axis=1)) #sort each row of X
#to find K smallest values in an array, Numpy provides np.partition() function. Check it out.

[[7 2 9 2 3 3]
 [2 3 4 1 2 9]
 [1 4 6 8 2 3]
 [0 0 6 0 6 3]]
***
[[0 0 4 0 2 3]
 [1 2 6 1 2 3]
 [2 3 6 2 3 3]
 [7 4 9 8 6 9]]
[[2 2 3 3 7 9]
 [1 2 2 3 4 9]
 [1 2 3 4 6 8]
 [0 0 0 3 6 6]]


Numpy's structured arrays and record arrays - provides efficient storage for compound hetergeneous data

In [25]:
data = np.zeros(3,dtype={'names':('name','age','weight'),'formats':('U10','i4','f8')}) #here we use compound data type
#for storing name,age and weights of people in a single structured array rather than storing these in 3 separate arrays
#'U10' translates to unicode string of maximum length 10, 'i4' translates to 4-byte integer and 'f8' translates to 
#8-byte float. This is the dictionary-method of creating structured arrays.
print(data.dtype)
name=['Alice','Bob','Cathy']
age=[25,30,29]
weight=[76.4,65.0,73.2]
#Now that we have created an empty container, we can fill the array with our list of values
data['name']=name
data['age']=age
data['weight']=weight
print(data) #data is now arranged together in one convinient block of memory

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('Alice', 25, 76.4) ('Bob', 30, 65. ) ('Cathy', 29, 73.2)]


In [30]:
#The handy thing with structured arrays is that we can now refer to arrays either by index or by name
print(data['name'])#get all names
print(data[0])#get the firdt row of data
print(data[-1]['name'])#get the name from the last row of data
print(data[data['age']<30]['name']) #get names where age is under 30
#To do more complicated operations from these, we should probably consider using the Pandas package which provides a 
#DataFrame object, which is a struture built on Numpy arrays that offers a variety of useful data manipulation
#functionality similar to the above and a lot more. To find out other ways of creating structured arrays other than 
#the dictionary-method and to know about record arrays, check out the book Python in Data science handbook page 
#number-112.

['Alice' 'Bob' 'Cathy']
('Alice', 25, 76.4)
Cathy
['Alice' 'Cathy']
